### ISSUE TITLE
Validate bundle list when creating or updating a profile

### ISSUE THREAD

**Issue by bcle** [arlonproj/arlon#6]
Right now, a profile's bundle list is an arbitrary string that the user provides. It's meant to be a comma separated list. The following validations should take place:
- The bundle names must follow k8s resource naming requirements (they can't have special characters, etc...)
- The list must be comma separated if more than one bundle
- (Optional, needs some thought) The bundle names must refer to valid existing bundles. This is trickier than it seems, for e.g., what happens when a bundle is deleted? We don't have a full relational database backing the objects, so can't express constraints.

Aha! Link: https://pf9.aha.io/features/ARLON-172

**Comment by Rohitrajak1807** [comment]
- (Optional, needs some thought) The bundle names must refer to valid existing bundles. This is trickier than it seems, for e.g., what happens when a bundle is deleted? We don't have a full relational database backing the objects, so can't express constraints.

@bcle is it okay to check if the bundle names exist using the list API we have for the `arlon bundle list` command? For now, that's the approach I'm taking.

- The list must be comma separated if more than one bundle **(this is taken care of)**
- The bundle names must follow k8s resource naming requirements (they can't have special characters, etc...) **(docs have some RFCs will do a regex validation for it.)**
