### ISSUE TITLE
arloncli shouldn't rely on argoCD logins every 24 hours

### ISSUE THREAD

**Issue by cre8minus1** [arlonproj/arlon#81]
the Arlon CLI depends on a current authenticated argocd CLI authentication existing on the users workstation. 
Arlon shouldn't have this dependency. 
Further, if it does it should inform the user that they need to login again OR just prompt the user and automatically log them in. 

 - [x] inform a user they need to log into ArgoCD when the token expires 
 - [ ] automatically log the user into argoCD 
 - [ ] remove the dependency on argocd

Aha! Link: https://pf9.aha.io/features/ARLON-139

**Comment by cruizen** [comment]
We definitely need to inform the user if they are not logged in to ArgoCD and their token has expired. We plan to do that. 

Automatically logging user into ArgoCD is not trivial since there are some variations. e.g. ArgoCD server may have been setup using SSO using one of the supported login providers.
